export type referenceType = {
    id: number, 
    imgUrl: string
}


export const referenceData: referenceType[] = [
    {id: 1, imgUrl: '/assets/references/Fichier 1.png'},
    {id: 2, imgUrl: '/assets/references/Fichier 2.png'},
    {id: 3, imgUrl: '/assets/references/Fichier 3.png'},
    {id: 4, imgUrl: '/assets/references/Fichier 4.png'},
    {id: 5, imgUrl: '/assets/references/Fichier 5.png'},
    {id: 6, imgUrl: '/assets/references/Fichier 6.png'},
    {id: 7, imgUrl: '/assets/references/Fichier 7.png'},
    {id: 8, imgUrl: '/assets/references/Fichier 8.png'},
    {id: 9, imgUrl: '/assets/references/Fichier 9.png'},
    {id: 10, imgUrl: '/assets/references/Fichier 10.png'},
    {id: 11, imgUrl: '/assets/references/Fichier 11.png'},
    {id: 12, imgUrl: '/assets/references/Fichier 12.png'},
    {id: 13, imgUrl: '/assets/references/Fichier 13.png'},
    {id: 14, imgUrl: '/assets/references/Fichier 14.png'},
    {id: 15, imgUrl: '/assets/references/Fichier 15.png'},
    {id: 16, imgUrl: '/assets/references/Fichier 16.png'},
    {id: 17, imgUrl: '/assets/references/Fichier 17.png'},
    {id: 18, imgUrl: '/assets/references/Fichier 18.png'},
    {id: 19, imgUrl: '/assets/references/Fichier 19.png'},
    {id: 20, imgUrl: '/assets/references/Fichier 20.png'},
    {id: 21, imgUrl: '/assets/references/Fichier 21.png'},
    {id: 22, imgUrl: '/assets/references/Fichier 22.png'},
    {id: 23, imgUrl: '/assets/references/Fichier 23.png'},
    {id: 24, imgUrl: '/assets/references/Fichier 24.png'},
    {id: 25, imgUrl: '/assets/references/Fichier 25.png'},
    {id: 26, imgUrl: '/assets/references/Fichier 26.png'},
    {id: 27, imgUrl: '/assets/references/Fichier 27.png'},
    {id: 28, imgUrl: '/assets/references/Fichier 28.png'},
    {id: 29, imgUrl: '/assets/references/Fichier 29.png'},
    {id: 30, imgUrl: '/assets/references/Fichier 30.png'},
    {id: 31, imgUrl: '/assets/references/Fichier 31.png'},
    {id: 32, imgUrl: '/assets/references/Fichier 32.png'},
    {id: 33, imgUrl: '/assets/references/Fichier 33.png'},
    {id: 34, imgUrl: '/assets/references/Fichier 34.png'},
    {id: 35, imgUrl: '/assets/references/Fichier 35.png'},
    {id: 36, imgUrl: '/assets/references/Fichier 36.png'},
    {id: 37, imgUrl: '/assets/references/Fichier 37.png'},
    {id: 38, imgUrl: '/assets/references/Fichier 38.png'},
    {id: 39, imgUrl: '/assets/references/Fichier 39.png'},
    {id: 40, imgUrl: '/assets/references/Fichier 40.png'},
    {id: 41, imgUrl: '/assets/references/Fichier 41.png'},
    {id: 42, imgUrl: '/assets/references/Fichier 42.png'},
    {id: 43, imgUrl: '/assets/references/Fichier 43.png'},
]