import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import {FirstNav, FooterComponent, Navbar} from "@/components";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn('relative min-h-screen',inter.className)}>
        <div className={'fixed w-full z-20 drop-shadow-md'}>
            <FirstNav/>
            <Navbar/>
        </div>
        {children}
        <FooterComponent/>
      </body>
    </html>
  );
}
